sudo: required

services:
  - docker

before_install:
  - docker build -t luiswitz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run luiswitz/react-test npm test -- --coverage

after_success:
  - docker build -t luiswitz/multi-client ./client
  - docker build -t luiswitz/multi-nginx ./nginx
  - docker build -t luiswitz/multi-server ./server
  - docker build -t luiswitz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push luiswitz/multi-client
  - docker push luiswitz/multi-nginx
  - docker push luiswitz/multi-server
  - docker push luiswitz/multi-worker

deploy:
  provider: elastibeanstalk
  region: us-west-2
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-west-2-599611906549 
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
