sudo: required

services:
  - docker

before_install:
  - docker build -t luiswitz/react-test -f ./client/Dockerfile.dev

scripts:
  - docker run luiswitz/react-test npm test -- --coverage

after_success:
  - docker build -t luiswitz/multi-client ./client
  - docker build -t luiswitz/multi-nginx ./nginx
  - docker build -t luiswitz/multi-server ./server
  - docker build -t luiswitz/multi-worker ./worker
  # login in docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push luiswitz/multi-client
  - docker push luiswitz/multi-nginx
  - docker push luiswitz/multi-server
  - docker push luiswitz/multi-worker
